name: wepei_module
description: WePeiYang Flutter module for HarmonyOS

version: 4.5.3+183

environment:
  sdk: ">=3.6.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  async: any
  numberpicker: any
  pointycastle: any
  xml: any
  syncfusion_flutter_barcodes: any
  badges: any
  connectivity_plus: any
  cached_network_image: any
  card_swiper: any
  dio: any
  dio_smart_retry: any
  dio_cookie_caching_handler:
    path: ./lib/commons/network/dio_cookie_cached_handler
  talker_flutter: any
  talker_dio_logger: any
  record: any
  extended_tabs: any
  extended_image: any
  shimmer: any
  flutter_displaymode: any
  flutter_html: any
  flutter_markdown: any
  flutter_rating_bar: any
  flutter_native_image: any
  flutter_screenutil: any
  flutter_smart_dialog: any
  flutter_svg: any
  fluttertoast: any
  gallery_saver_plus: any
  http_parser: any
  glass_kit: any
  frosted_glass_effect: any
  image_cropper: any
  image_picker: any
  like_button: any
  linkfy_text:
    git:
      url: https://github.com/Iamstanlee/linkfy_text.git
  mutex: any
  path_provider: any
  permission_handler: any
  photo_view: any
  provider: any
  pull_to_refresh: any
  retry: any
  flutter_reorderable_grid_view: any
  screenshot: any
  share_plus: any
  shared_preferences: any
  simple_html_css: any
  simple_url_preview_v2:
    git:
      url: https://github.com/hxphieno/flutter-simple-url-preview_2.git
  flutter_link_previewer: any
  table_calendar: any
  url_launcher: any
  uuid: any
  webview_flutter: any
  wechat_picker_library: any
  wechat_assets_picker: any
  window_manager: any
  waterfall_flow: any
  image_size_getter: any
  flutter_staggered_grid_view: any
  transparent_image: any
  package_info_plus: any
  glass: any
  qr_code_tools: any
  photo_manager: any
  cupertino_icons: any
  dio_cookie_manager: any
  cookie_jar: any

dev_dependencies:
  flutter_lints: any
  build_runner: any

dependency_overrides:
  photo_manager: 3.6.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/ai/
    - assets/images/calender/
    - assets/images/school_map/
    - assets/images/account/
    - assets/images/account/1.5x/
    - assets/images/account/2.0x/
    - assets/images/account/3.0x/
    - assets/images/account/4.0x/
    - assets/images/schedule/
    - assets/images/studyroom_icons/
    - assets/images/lake_butt_icons/
    - assets/images/lost_and_found_icons/
    - assets/svg_pics/
    - assets/svg_pics/ai_icons/
    - assets/svg_pics/lake_butt_icons/
    - assets/svg_pics/laf_butt_icons/
    - privacy/
  fonts:
    - family: Fourche
      fonts:
        - asset: assets/fonts/en/SFFourcheBoldItalic.ttf
          style: italic
    - family: Swis
      fonts:
        - asset: assets/fonts/en/Swis721-Blk-BT-Black-2.ttf
    - family: ProductSans
      fonts:
        - asset: assets/fonts/en/ProductSans-Bold.ttf
        - asset: assets/fonts/en/ProductSans-Regular.ttf
  module:
    androidX: true
    androidPackage: com.twtservice.wepeiyang
    iosBundleIdentifier: com.twtservice.wepeiyang
    ohosBundleName: com.weipeiyang.cn
